🚀 Redirect to groupexpense or expense in activity list based on groupId
oss-apps/split-pro pull request #140
Opened 2024-10-29 16:11 UTC by alexanderwassbjer

Redirect the user to the group expense page instead of the expense page if its a group expense.

May be related to: https://github.com/oss-apps/split-pro/issues/130

2024-10-29 16:12 UTC, alexanderwassbjer commented
@KMKoushik Ready to be reviewed

2024-10-31 09:54 UTC, KMKoushik requested changes

2024-10-31 09:54 UTC, KMKoushik commented on src/pages/activity.tsx
> +                    href={`${e.expense.groupId ? `/groups/${e.expense.groupId}/` : '/'}expenses/${e.expenseId}`}
it's just directing to group?

2024-10-31 09:55 UTC, KMKoushik approved these changes

2024-10-31 09:55 UTC, merged

2024-10-31 09:56 UTC, alexanderwassbjer commented
Thanks!